#CLAIM
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: ${{values.system}}-${{values.env}}-db
spec:
  forProvider:
    region: us-east-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "9.6"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: ${{values.system}}
    name: ${{values.system}}-${{values.env}}-db