apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sre
  title: Community SRE Team
spec:
  type: team
  picture: https://api.dicebear.com/7.x/identicon/svg?seed=Fluffy&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: paulofponciano@gmail.com
spec:
  profile:
    displayName: Paulo Ponciano
    email: paulofponciano@gmail.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Leo&backgroundColor=transparent
  memberOf: [sre]