# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: 'Z2hwX09KMmlWWWJaaWZDV2x6bHFrZU82bndIQml1S3pEUzRSN1NsMg==' # base 64