---
apiVersion: v1
kind: Service
metadata:
  name: ${{values.component_id}}-service
  namespace: ${{values.component_id}}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${{values.component_id}}.pauloponciano.digital
  labels:
    app: ${{values.component_id}}
    version: 0.0.1
    backstage.io/kubernetes-id: ${{values.component_id}}
spec:
  type: ClusterIP
  ports:
  - name: tcp-node
    port: 8080
  selector:
    app: ${{values.component_id}}