apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: keycloak
  title: KeyCloak
  description: Keycloak.
  links:
    - url: https://www.keycloak.org/documentation
      title: Documentation
      icon: web
spec:
  type: identity-provider
  lifecycle: production
  owner: community-authors
  system: community-idp